### ISSUE TITLE
Use Files instead of NamePipes.

### ISSUE THREAD

**Issue by LocalCommunist** [rakion99/IceMeme#40]
NamePipes have a limit on the buffer. Use Files instead.

**Comment by rakion99** [comment]
Indeed NampedPipes is limited for Write but only in Windows Server 2003 and Windows XP

> **Windows Server 2003 and Windows XP:  Pipe write operations across a network are limited in size per write. The amount varies per platform. For x86 platforms it's 63.97 MB. For x64 platforms it's 31.97 MB. For Itanium it's 63.95 MB. For more information regarding pipes, see the Remarks section.**

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365747(v=vs.85).aspx

anyways since both luac and lua are limited there no need to swtich to text files or sockets since there no big scripts that will work so for now its fine i guess

**Comment by rakion99** [comment]
in short words you only need to change the buffer and you will be ok, for c# client named pipe you only need to change streamwriter buffer size, i have update the ui with these changes so you can see how i changed the buffer size 😃
