### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by ramington** [rakion99/IceMeme#49]
Can you add icesource cpp file?

**Comment by Angelbooy** [comment]
holy shit just make it

**Comment by rakion99** [comment]
find it yourself.... if you were smart you could just use google and found it in seconds, but since you just wanna skid and C&P you didn't know that.
and im sure that you don't even know c++...... so if you wanna keep "exploiting" first learn c++, you don't need sources that you don't even know what do or understand so stop right there and start learning c++, this is not for people that only know what is a DWORD LOL
